apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - rbac/role.yaml
  - deployment.yaml
  - service.yaml


images:
  - name: pronoea
    newName: xingba/pronoea
    newTag: 0.0.6