---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pronoea-admin
rules:
- apiGroups:
  - pronoea.io
  resources:
  - probes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pronoea.io
  resources:
  - probes/finalizers
  verbs:
  - update
- apiGroups:
  - pronoea.io
  resources:
  - probes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
# https://kubernetes.io/docs/reference/access-authn-authz/rbac/
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pronoea
---
# https://kubernetes.io/docs/reference/access-authn-authz/rbac/
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrolebinding
subjects:
- kind: ServiceAccount
  name: pronoea
roleRef:
  kind: ClusterRole
  name: pronoea-admin
  apiGroup: rbac.authorization.k8s.io
---

